name: Clojure CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: setup clojure
      uses: DeLaGuardo/setup-clojure@13.4
      with:
        lein: latest        
    - name: Install dependencies
      run: lein deps
    - name: Run tests
      run: lein test
